
const SNS_REGION = process.env.SNS_REGION ?? "us-east-2"
const NEW_LEAD_TOPIC_ARN = process.env.NEW_LEAD_TOPIC_ARN ?? ""
const NEXT_PUBLIC_TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY ?? ""
const TURNSTILE_SECRET_KEY = process.env.TURNSTILE_SECRET_KEY ?? ""
const TURNSTILE_VALIDATION_ENDPOINT = process.env.TURNSTILE_VALIDATION_ENDPOINT

export default {
    SNS_REGION,
    NEW_LEAD_TOPIC_ARN,
    NEXT_PUBLIC_TURNSTILE_SITE_KEY,
    TURNSTILE_SECRET_KEY,
    TURNSTILE_VALIDATION_ENDPOINT,
}