
const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID ?? ""
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY ?? ""
const AWS_REGION = process.env.AWS_REGION ?? ""
const NEW_LEAD_TOPIC_ARN = process.env.NEW_LEAD_TOPIC_ARN ?? ""
const NEXT_PUBLIC_TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY ?? ""
const TURNSTILE_SECRET_KEY = process.env.TURNSTILE_SECRET_KEY ?? ""
const TURNSTILE_VALIDATION_ENDPOINT = process.env.TURNSTILE_VALIDATION_ENDPOINT

export default {
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_REGION,
    NEW_LEAD_TOPIC_ARN,
    NEXT_PUBLIC_TURNSTILE_SITE_KEY,
    TURNSTILE_SECRET_KEY,
    TURNSTILE_VALIDATION_ENDPOINT,
}